### ISSUE TITLE
Ability to flatten attributes from nested models

### ISSUE THREAD

**Issue by bradurani** [trunkclub/faceted#10]
It would be nice if I could do something like:

module MyApi
  class Musician
    include Faceted::Presenter
    presents :musician
    field :name
    field :genre
    field :instrument, :default => 'guitar'
    field :birthplace_id, :flattened
  end
end

And have the birthplace attributes added directly to the Musician attributes, rather then nested another level deep. It's a pretty common use case in my experience that a single API response disguises the fact that it returns data from multiple tables.

**Comment by CoralineAda** [comment]
The way that I have addressed this is by adding methods to the presenter:

```
def birthplace_city
  self.birthplace.city_name
end
```

The complication otherwise comes from having to save association attributes back through the presenter. 

Open to alternatives!
